import React from "react";
import "./grid.css";

export default function Grid() {
  return (
    <div id="skills" className="grid-container">
      <header className="grid-header">
        <h1>Skills</h1>
        <p>
          I have experience with a variety of technologies and tools. Here are a
          few of them
        </p>
        <p>
          More details below! <i class="fa-solid fa-arrow-down"></i>{" "}
        </p>
      </header>
      <div className="grid">
        <img
          alt="html"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/html.png"
          }
        />
        <img
          alt="css"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/css.png"
          }
        />
        <img
          alt="javascript"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/js.png"
          }
        />
        <img
          alt="react"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/react.png"
          }
        />
        <img
          alt="bootstrap"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/bootstrap.png"
          }
        />
        <img
          alt="vscode"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/vscode.png"
          }
        />
        <img
          alt="node"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/node.png"
          }
        />
        <img
          alt="npm"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/npm.png"
          }
        />
        <img
          alt="github"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/github.png"
          }
        />
        <img
          alt="figma"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/figma.png"
          }
        />
        <img
          alt="ruby"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/ruby.png"
          }
        />
        <img
          alt="rails"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/rails.png"
          }
        />
        <img
          alt="express"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/express.png"
          }
        />
        <img
          alt="aws"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/aws.png"
          }
        />
        <img
          alt="webflow"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/webflow.png"
          }
        />
        <img
          alt="xcode"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/xcode.png"
          }
        />
        <img
          alt="mongodb"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/mongodb.png"
          }
        />
        <img
          alt="postgresql"
          src={
            "https://sel-dev-bucket.s3.us-east-1.amazonaws.com/portfolio-images/dev-icons/dev_icons/postgresql.png"
          }
        />
      </div>
    </div>
  );
}
